### ISSUE TITLE
Icon on profile categories not displaying

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#175]
Rel 0.11

https://trello.com/c/jUbY7O5S/600-icon-on-profile-categories-not-displaying

**Comment by emre2038** [comment]
On `all_details` endpoint we need the icon data for each categories, but we don't have that currently @milafrerichs @adieyal

**Comment by milafrerichs** [comment]
@emre2038 just assume that the BE is sending the data and make the changes to the FE code. 

```diff
[
  {
    "name": "Health",
    "id": 43,
    "icon": "local_hospital",
    "subthemes": [
      {
        "label": "Pharmacies",
        "id": 300,
        "count": 1500,
+       "icon": "local_hospital"
        "metadata": {
          "source": "",
          "description": "",
          "licence": 1
        }
      },
    ]
  },

**Comment by emre2038** [comment]
I thought this issue was about the categories on rich data panel or data mapper
![image](https://user-images.githubusercontent.com/53019884/104157828-06bfda80-53fd-11eb-941a-7e89e44ef3f7.png)

with the current version of staging the icons on point mapper looks fine to me
![image](https://user-images.githubusercontent.com/53019884/104157901-2951f380-53fd-11eb-9dc0-3189c9fb405c.png)

am I missing something?

**Comment by milafrerichs** [comment]
@emre2038 it's about the subcategory items being missing:

![Bildschirmfoto 2021-01-11 um 12 22 08](https://user-images.githubusercontent.com/688980/104176597-cdd93300-5407-11eb-9363-a584879f44fb.png)
